### ISSUE TITLE
psp2-fixup crashing on 32 bit OS

### ISSUE THREAD

**Issue by xerpi** [psp2dev/psp2sdk#45]
psp2-fixup segfaults on 32 bit OS, gdb backtrace:
```
Starting program: /usr/local/bin/psp2-fixup -q -S FTPVita.elf FTPVita_fixup.elf

Program received signal SIGSEGV, Segmentation fault.
0xb7e8ae16 in _int_free (av=0xb7fc1420 <main_arena>, p=<optimized out>, 
    have_lock=0) at malloc.c:3996
3996	malloc.c: No such file or directory.
(gdb) bt
#0  0xb7e8ae16 in _int_free (av=0xb7fc1420 <main_arena>, 
    p=<optimized out>, have_lock=0) at malloc.c:3996
#1  0x0804a7e0 in closeElf (elf=elf@entry=0xbfffef94) at elf.c:114
#2  0x0804894b in main (argc=5, argv=0xbffff0c4) at psp2-fixup.c:120
```

**Comment by 173210** [comment]
Fixed with pull request #54 .
